/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as HomeRouteImport } from './routes/home'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AddRouteImport } from './routes/add'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeadlineIdRouteImport } from './routes/deadline.$id'
import { Route as BlockedIdRouteImport } from './routes/blocked.$id'
import { Route as AnalysisIdRouteImport } from './routes/analysis.$id'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeadlineIdRoute = DeadlineIdRouteImport.update({
  id: '/deadline/$id',
  path: '/deadline/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BlockedIdRoute = BlockedIdRouteImport.update({
  id: '/blocked/$id',
  path: '/blocked/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisIdRoute = AnalysisIdRouteImport.update({
  id: '/analysis/$id',
  path: '/analysis/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/calendar': typeof CalendarRoute
  '/home': typeof HomeRoute
  '/insights': typeof InsightsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/tasks': typeof TasksRoute
  '/analysis/$id': typeof AnalysisIdRoute
  '/blocked/$id': typeof BlockedIdRoute
  '/deadline/$id': typeof DeadlineIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/calendar': typeof CalendarRoute
  '/home': typeof HomeRoute
  '/insights': typeof InsightsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/tasks': typeof TasksRoute
  '/analysis/$id': typeof AnalysisIdRoute
  '/blocked/$id': typeof BlockedIdRoute
  '/deadline/$id': typeof DeadlineIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/calendar': typeof CalendarRoute
  '/home': typeof HomeRoute
  '/insights': typeof InsightsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/tasks': typeof TasksRoute
  '/analysis/$id': typeof AnalysisIdRoute
  '/blocked/$id': typeof BlockedIdRoute
  '/deadline/$id': typeof DeadlineIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add'
    | '/calendar'
    | '/home'
    | '/insights'
    | '/onboarding'
    | '/profile'
    | '/tasks'
    | '/analysis/$id'
    | '/blocked/$id'
    | '/deadline/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add'
    | '/calendar'
    | '/home'
    | '/insights'
    | '/onboarding'
    | '/profile'
    | '/tasks'
    | '/analysis/$id'
    | '/blocked/$id'
    | '/deadline/$id'
  id:
    | '__root__'
    | '/'
    | '/add'
    | '/calendar'
    | '/home'
    | '/insights'
    | '/onboarding'
    | '/profile'
    | '/tasks'
    | '/analysis/$id'
    | '/blocked/$id'
    | '/deadline/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  CalendarRoute: typeof CalendarRoute
  HomeRoute: typeof HomeRoute
  InsightsRoute: typeof InsightsRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  TasksRoute: typeof TasksRoute
  AnalysisIdRoute: typeof AnalysisIdRoute
  BlockedIdRoute: typeof BlockedIdRoute
  DeadlineIdRoute: typeof DeadlineIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deadline/$id': {
      id: '/deadline/$id'
      path: '/deadline/$id'
      fullPath: '/deadline/$id'
      preLoaderRoute: typeof DeadlineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocked/$id': {
      id: '/blocked/$id'
      path: '/blocked/$id'
      fullPath: '/blocked/$id'
      preLoaderRoute: typeof BlockedIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis/$id': {
      id: '/analysis/$id'
      path: '/analysis/$id'
      fullPath: '/analysis/$id'
      preLoaderRoute: typeof AnalysisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  CalendarRoute: CalendarRoute,
  HomeRoute: HomeRoute,
  InsightsRoute: InsightsRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  TasksRoute: TasksRoute,
  AnalysisIdRoute: AnalysisIdRoute,
  BlockedIdRoute: BlockedIdRoute,
  DeadlineIdRoute: DeadlineIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
